### ISSUE TITLE
Support Cedar/SLURM

### ISSUE THREAD

**Issue by raamana** [raamana/oppni#14]
- support multiple project allocations for SLURM `hpc_directives.append('#SBATCH --account def-sstrothe')
`
 - check with Stephen to finalize versions of AFNI
 - or get libXp installed for Cedar
 - octave version incompatibility -- have them installed to the common folder (like Pradeep's and refer to that location) preferably
 - check for presence of matlab before querying for matlab version : version_info["matlab"] 
 - change workdir to chdir for SLURM

**Comment by mprati** [comment]
all above items have been addressed.

**Comment by raamana** [comment]
Thanks Mark! do you want me to merge #19 now?

**Comment by mprati** [comment]
Hi Pradeep,

yes thanks.

It's confusing having git set up on my personal email.

Just sent you a request from my baycrest account.

regards
Mark

**Comment by mprati** [comment]
HI Pradeep, yes can you merge #19 thanks
